# Numpy
- open scorce library
- used to work with numerical data
- contains multi dimensional array and matrix structures


In [1]:
#Install numpy
!pip install numpy

In [2]:
# import
import numpy as np

## Why Numpy?

- High Performance: Optimized for numerical computations.
- Multidimensional Arrays: Provides ndarray for N-dimensional array representation.
- Broadcasting: Enables arithmetic operations on arrays of different shapes.
- Comprehensive Mathematical Functions: Includes a wide range of mathematical operations.
-Memory Efficiency: More memory-efficient than Python lists.
-Integration with Other Libraries: Compatible with pandas, SciPy, scikit-learn, TensorFlow, etc.
-Vectorization: Allows execution of operations on entire arrays without explicit loops.
-Ease of Use: Simple syntax with powerful functionality.
-Community and Support: Extensive documentation, tutorials, and active community support.

## Numpy class

- **ndarray.ndim :** Number of dimensions of the array.
- **ndarray.shape :** Dimensions of the array (rows, columns).
- **ndarray.size :** Total number of elements in the array.
- **ndarray.dtype :** Data type of the elements in the array.
-**ndarray.itemsize :** Size (in bytes) of each element in the array.
- **ndarray.data :** 	Memory buffer containing the actual elements of the array.


In [3]:
a=np.array(([1,2,3],[8,5,4]))
print("Number of dimensions of the array=",a.ndim)
print( )
print("Dimensions of the array=", a.shape)
print( )
print("Total number of elements in the array=", a.shape)
print( )
print("Data type of the elements in the array", a.dtype)
print( )
print("Size (in bytes) of each element in the array",a.itemsize)
print( )
print("Memory buffer containing the actual elements of the array", a.data)

Number of dimensions of the array= 2

Dimensions of the array= (2, 3)

Total number of elements in the array= (2, 3)

Data type of the elements in the array int64

Size (in bytes) of each element in the array 8

Memory buffer containing the actual elements of the array <memory at 0x7b848df0c790>


## Complex

In [4]:
c=np.array([[1,2,3],[4,5,6]], dtype=complex)
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

## Create sequences of numbers

In [5]:
# np.arange([start,stop,step], dtype=None)
c=np.arange(10,50,5)
c

array([10, 15, 20, 25, 30, 35, 40, 45])

In [6]:
# float
np.arange(0,2,0.4)

array([0. , 0.4, 0.8, 1.2, 1.6])

In [7]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])


##Vectors - Arithmetic operators


In [9]:
x=np.array([1,2,3])
y=np.array([4,5,6])
c=x+y
c

array([5, 7, 9])

In [15]:
a=np.array([20,40,50,30])
b=np.arange(4)
c= a - b
c
#output:
# b=[0,1,2,3]
#c=[20-0,40-1,50-2,30-3]

array([20, 39, 48, 27])

In [17]:
#Element-wise multiplication
x=np.array([1,2,3])
y=np.array([4,5,6])
d=x*y
d

array([ 4, 10, 18])

In [21]:
# Scaling vectors
x=np.array([1,2,3])
y=5*x
y

array([ 5, 10, 15])

In [23]:
#Element-wise functions of vectors
x=np.array([1,2,3])
y=3**x
y

array([ 3,  9, 27])

In [24]:
# log
x = np.array([1, 10, 100, 1000, 10000, 100000])
y = np.log10(x)
y

array([0., 1., 2., 3., 4., 5.])

In [25]:
# Natural log
x = np.array([1, np.e, np.e ** 2])
y = np.log(x)
y

array([0., 1., 2.])

In [27]:
# Dot Product
x = np.array([1, 2, 3, 4])
y = np.array([-4, -5, -6, -7])

z = np.dot(x, y)
z

# x*y=[1(-4)+2(-5)+3(-6)+4(-7)]

-60

## Matrix

In [31]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

In [33]:
#addition
D=A+B
D

array([[3, 1],
       [3, 5]])

In [32]:
# elementwise product
C=A*B
C

array([[2, 0],
       [0, 4]])

In [29]:
# matrix product
A@B

array([[5, 4],
       [3, 4]])

In [30]:
# dot matrix product
B.dot(A)

array([[2, 2],
       [3, 7]])

In [35]:
# Scaling a matrix
M = np.array([[1, 3, 3], [4, 4, 6], [7, 7, 9]])
P = 3 * M
P

array([[ 3,  9,  9],
       [12, 12, 18],
       [21, 21, 27]])

In [37]:
#Transpose of a matrix
M = np.array([[1, 3, 3], [3, 5, 6]])
M_t = np.transpose(M)
M_t

array([[1, 3],
       [3, 5],
       [3, 6]])

In [39]:
#another way for transpose of matrix
M = np.array([[1, 6, 3], [4, 8, 6]])
M_t = M.T

M_t

array([[1, 4],
       [6, 8],
       [3, 6]])

## Product of matrix and vector

In [40]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x

C

array([ 44, 107, 170])

## Matrix of ones

In [43]:
M= np.ones((3,2))
M

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Identity matrix

In [44]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# More on Arrays

## Arrays

In [45]:
x = np.array([1, 4, 3])
M = np.array([[1, 2], [5, 4], [5, 6]])

print('x has shape', x.shape)
print('M has shape', M.shape)

print('x is an array of dimension', x.ndim)
print('M is an array of dimension', M.ndim)


x has shape (3,)
M has shape (3, 2)
x is an array of dimension 1
M is an array of dimension 2


## Reshaping

In [51]:
M=np.array([[1,2,3],[4,5,6]])
x=M.reshape(6) #6 element
x

array([1, 2, 3, 4, 5, 6])

In [57]:
x=np.array([1, 2, 3, 4, 5, 6])
M=x.reshape((2,3))
N=x.reshape(3,2)
print(M)
print()
print(N)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [59]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)

# M+b is not possible
# Because M is a 2D array (or matrix) with the shape (2, 4), which means it has 2 rows and 4 columns.
# b is a 1D array (or vector) with the shape (2,), which means it has 2 elements.

Shape of M: (2, 4)
Shape of b: (2,)


In [60]:
b = np.expand_dims(b, 1)
b.shape

(2, 1)

## Indexing and Slicing an array

In [61]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[2]

array([5, 6])

In [62]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
M[1: 3, 0]

array([3, 5])

## Stacking arrays

In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.concatenate((A, B), axis = 0)
print(C.shape)
print(C)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [65]:
C = np.concatenate((A,B),axis=1)
C

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Sum, Mean and Variance

In [71]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rsum = np.sum(A, axis = 1)
print("sum of rows:",rsum)
#output ([1+2+3+4 , 5+6+7+8])

sum of rows: [10 26]


In [72]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
csum = np.sum(A, axis = 0)
print("sum of columns:",csum)
#output(1+5,2+6,3+7,4+8)

sum of columns: [ 6  8 10 12]


# Linespace
np.linspace(a, b, n) is a method that returns an array of 𝑛 evenly spaced points between [𝑎,𝑏].


For example, np.linspace(0, 1, 5) is the array [0., 0.25, 0.5, 0.75, 1.].

In [6]:
x = np.linspace(-1, 1, 5)
y = 2 * x

#x=(-1,-0.5,0,0.5,1)
#y=2*(-1,-0.5,0,0.5,1)

array([-2., -1.,  0.,  1.,  2.])

In [7]:
x = np.linspace(-1, 1, 5)
y = 2 * x+4
y
#y=2*(-1,-0.5,0,0.5,1)+4

array([2., 3., 4., 5., 6.])

- **"*" Operator (Element-wise Multiplication):**
      - The * operator performs element-wise multiplication between arrays.
      - This means that each element in one array is multiplied by the corresponding element in another array.
      - The arrays must have the same shape or be broadcastable to a common shape.

- **@ Operator: Matrix multiplication**
      - It is used for matrix multiplication (also known as the dot product when applied to vectors).
      - It follows the rules of linear algebra where the rows of the first matrix
       are multiplied by the columns of the second matrix.

- **np.dot Function:**
       The np.dot function is a more general function that can be used for both dot products
       and matrix multiplication, depending on the input arrays:
       - If both arguments are 1-D arrays, it performs the dot product.
       - If both arguments are 2-D arrays, it performs matrix multiplication.
       - If one argument is a 2-D array and the other is a 1-D array, it performs a matrix-vector multiplication.
       - For N-dimensional arrays, it performs a sum-product over the last axis of the first array
       and the second-to-last axis of the second array.